# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test the project

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # follows https://en.wikipedia.org/wiki/Java_version_history#Release_table
        versions: [
          { java: '11', gradle: 'wrapper' },
          { java: '17', gradle: 'wrapper' },
          { java: '21', gradle: 'wrapper' },
          { java: '25', gradle: 'current' },
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java ${{ matrix.versions.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.versions.java }}
        distribution: 'temurin'

    - name: Setup Gradle ${{ matrix.versions.gradle }}
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: ${{ matrix.versions.gradle }}

    - name: Build & Test
      run: gradle build test
